In [9]:
import tensorflow as tf
tensor_z=tf.constant(4)
print(tensor_z)
print(tensor_z.ndim)

tf.Tensor(4, shape=(), dtype=int32)
0


In [13]:
t_two=tf.constant([[[[[2,-3,2],
                   [3,4,5]],
                   [[5,-5,10],[3,4,5]],[[2,6,7],[4,5,6]]],
                  [[[2,-3,2],
                   [3,4,5]],
                   [[5,-5,10],[3,4,5]],[[2,6,7],[4,5,6]]]],[[[[2,-3,2],
                   [3,4,5]],
                   [[5,-5,10],[3,4,5]],[[2,6,7],[4,5,6]]],
                  [[[2,-3,2],
                   [3,4,5]],
                   [[5,-5,10],[3,4,5]],[[2,6,7],[4,5,6]]]]], shape=(2, 2, 3, 2, 3), dtype=tf.float32)
print(t_two)
print(t_two.ndim)
 

tf.Tensor(
[[[[[ 2. -3.  2.]
    [ 3.  4.  5.]]

   [[ 5. -5. 10.]
    [ 3.  4.  5.]]

   [[ 2.  6.  7.]
    [ 4.  5.  6.]]]


  [[[ 2. -3.  2.]
    [ 3.  4.  5.]]

   [[ 5. -5. 10.]
    [ 3.  4.  5.]]

   [[ 2.  6.  7.]
    [ 4.  5.  6.]]]]



 [[[[ 2. -3.  2.]
    [ 3.  4.  5.]]

   [[ 5. -5. 10.]
    [ 3.  4.  5.]]

   [[ 2.  6.  7.]
    [ 4.  5.  6.]]]


  [[[ 2. -3.  2.]
    [ 3.  4.  5.]]

   [[ 5. -5. 10.]
    [ 3.  4.  5.]]

   [[ 2.  6.  7.]
    [ 4.  5.  6.]]]]], shape=(2, 2, 3, 2, 3), dtype=float32)
5


In [14]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [17]:
t_tensor=tf.convert_to_tensor(arr)
print(t_tensor)


tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [19]:
eten=tf.eye(
  num_rows=3,
  num_columns=None,
  batch_shape=None,
  dtype=tf.dtypes.bool,
  name=None
  
)
print(eten)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)
